version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rpsls_db
      POSTGRES_USER: rpsls_user
      POSTGRES_PASSWORD: rpsls_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpsls_user -d rpsls_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Game Logic Service
  game-logic:
    build:
      context: ./services/game_logic
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=game-logic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Player Management Service
  player-management:
    build:
      context: ./services/player_management
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - SERVICE_NAME=player-management
      - DATABASE_URL=postgresql+asyncpg://rpsls_user:rpsls_password@postgres:5432/rpsls_db
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Matchmaking Service
  matchmaking:
    build:
      context: ./services/matchmaking
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - SERVICE_NAME=matchmaking
      - GAME_LOGIC_SERVICE_URL=http://game-logic:8000
      - PLAYER_SERVICE_URL=http://player-management:8001
      - HISTORY_SERVICE_URL=http://game-history:8003
      - RANDOM_API_URL=https://codechallenge.boohma.com/random
    depends_on:
      - game-logic
      - player-management
      - game-history
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Game History Service
  game-history:
    build:
      context: ./services/game_history
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - SERVICE_NAME=game-history
      - DATABASE_URL=postgresql+asyncpg://rpsls_user:rpsls_password@postgres:5432/rpsls_db
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: 