version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: rpsls_db
      POSTGRES_USER: rpsls_user
      POSTGRES_PASSWORD: rpsls_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpsls_user -d rpsls_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Game Service (FastAPI)
  game:
    build:
      context: ./services/game
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://rpsls_user:rpsls_password@postgres:5432/rpsls_db
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: 